name: seenx
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - absl-py=2.3.1=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py310h682ed8b_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - aom=3.9.1=h7bae524_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - astunparse=1.6.3=pyhd8ed1ab_3
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - audioread=3.0.1=py310hbe9552e_3
  - aws-c-auth=0.8.1=hfc2798a_0
  - aws-c-cal=0.8.1=hc8a0bd2_3
  - aws-c-common=0.10.6=h5505292_0
  - aws-c-compression=0.3.0=hc8a0bd2_5
  - aws-c-event-stream=0.5.0=h54f970a_11
  - aws-c-http=0.9.2=h96aa502_4
  - aws-c-io=0.15.3=haba67d1_6
  - aws-c-mqtt=0.11.0=h24f418c_12
  - aws-c-s3=0.7.9=hf37e03c_1
  - aws-c-sdkutils=0.2.2=hc8a0bd2_0
  - aws-checksums=0.2.2=hc8a0bd2_4
  - aws-crt-cpp=0.29.9=ha81f72f_2
  - aws-sdk-cpp=1.11.489=h0e5014b_0
  - azure-core-cpp=1.14.0=hd50102c_0
  - azure-identity-cpp=1.10.0=hc602bab_0
  - azure-storage-blobs-cpp=12.13.0=h7585a09_1
  - azure-storage-common-cpp=12.8.0=h9ca1f76_1
  - azure-storage-files-datalake-cpp=12.12.0=hcdd55da_1
  - brotli=1.1.0=h6caf38d_4
  - brotli-bin=1.1.0=h6caf38d_4
  - brotli-python=1.1.0=py310h1af2607_4
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h6a3b0d2_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=1.17.1=py310h497396d_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310h7f4e7e6_0
  - cpython=3.10.19=py310hd8ed1ab_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - datasets=2.14.4=pyhd8ed1ab_0
  - dav1d=1.2.1=hb547adb_0
  - dbus=1.16.2=hda038a8_0
  - debugpy=1.8.17=py310h7b404bc_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dill=0.3.7=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=hec049ff_0
  - ffmpeg=7.1.1=gpl_h20db955_106
  - filelock=3.20.0=pyhd8ed1ab_0
  - flatbuffers=24.12.23=h28594ff_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py310hf4fd40f_0
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - frozenlist=1.7.0=py310ha18c8e3_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gast=0.6.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.12=h7af3d76_3
  - gettext=0.25.1=h3dcc1bd_0
  - gettext-tools=0.25.1=h493aca8_0
  - gflags=2.2.2=hf9b8971_1005
  - giflib=5.2.2=h93a5062_0
  - glog=0.7.1=heb240a5_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py310h1b1a8f9_2
  - google-pasta=0.2.0=pyhd8ed1ab_2
  - graphite2=1.3.14=hec049ff_2
  - grpcio=1.67.1=py310h92b281b_2
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.13.0=nompi_py310h8ca6390_100
  - harfbuzz=11.4.5=hf4e55d4_0
  - hdf5=1.14.3=nompi_ha698983_109
  - hf-xet=1.2.0=py310h6ce4931_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - imageio=2.37.0=pyhfb79c49_0
  - imageio-ffmpeg=0.6.0=pyhd8ed1ab_0
  - imath=3.1.12=h025cafa_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=8.37.0=pyh8f84b5b_0
  - ipywidgets=8.1.5=pyhd8ed1ab_1
  - jasper=4.2.8=hc0e5025_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - keras=3.11.2=pyh753f3f9_0
  - kiwisolver=1.4.9=py310h563d721_2
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20240722.0=cxx17_h07bc746_4
  - libaec=1.1.4=h51d1e36_0
  - libarrow=19.0.0=h0945df6_9_cpu
  - libarrow-acero=19.0.0=hf07054f_9_cpu
  - libarrow-dataset=19.0.0=hf07054f_9_cpu
  - libarrow-substrait=19.0.0=h4239455_9_cpu
  - libasprintf=0.25.1=h493aca8_0
  - libasprintf-devel=0.25.1=h493aca8_0
  - libass=0.17.3=h68e5b86_2
  - libavif16=1.3.0=hf1e31eb_0
  - libblas=3.9.0=38_h51639a9_openblas
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.9.0=38_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.17.0=hdece5d2_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=hd74edd7_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.4=hca03da5_1
  - libflac=1.4.3=hb765f3a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgettextpo=0.25.1=h493aca8_0
  - libgettextpo-devel=0.25.1=h493aca8_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libglib=2.84.4=h7a3292d_0
  - libgoogle-cloud=2.35.0=hdbe95d5_0
  - libgoogle-cloud-storage=2.35.0=h7081f7f_0
  - libgrpc=1.67.1=h0a426d6_2
  - libhwloc=2.12.1=default_h88f92a7_1000
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libintl-devel=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.9.0=38_hd9741b5_openblas
  - liblapacke=3.9.0=38_h1b118fd_openblas
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libml_dtypes-headers=0.5.3=h707e725_0
  - libnghttp2=1.67.0=hc438710_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopencv=4.11.0=headless_py310hb767cdf_2
  - libopentelemetry-cpp=1.18.0=h0c05b2d_1
  - libopentelemetry-cpp-headers=1.18.0=hce30654_1
  - libopenvino=2025.0.0=h3f17238_2
  - libopenvino-arm-cpu-plugin=2025.0.0=h3f17238_2
  - libopenvino-auto-batch-plugin=2025.0.0=h7f72211_2
  - libopenvino-auto-plugin=2025.0.0=h7f72211_2
  - libopenvino-hetero-plugin=2025.0.0=h718ad69_2
  - libopenvino-ir-frontend=2025.0.0=h718ad69_2
  - libopenvino-onnx-frontend=2025.0.0=h76e6831_2
  - libopenvino-paddle-frontend=2025.0.0=h76e6831_2
  - libopenvino-pytorch-frontend=2025.0.0=h286801f_2
  - libopenvino-tensorflow-frontend=2025.0.0=he275e1d_2
  - libopenvino-tensorflow-lite-frontend=2025.0.0=h286801f_2
  - libopus=1.5.2=h48c0fde_0
  - libparquet=19.0.0=h636d7b7_9_cpu
  - libpng=1.6.50=h280e0eb_1
  - libprotobuf=5.28.3=h3bd63a1_1
  - libre2-11=2024.07.02=h07bc746_2
  - librosa=0.11.0=pyhd8ed1ab_0
  - librsvg=2.58.4=h266df6f_3
  - libsndfile=1.2.2=h9739721_1
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.0=h8adb53f_0
  - libssh2=1.11.1=h1590b86_0
  - libtensorflow_cc=2.18.0=cpu_hf321e49_1
  - libtensorflow_framework=2.18.0=cpu_h2398287_1
  - libthrift=0.21.0=h64651cc_0
  - libtiff=4.7.0=hfce79cd_1
  - libtorch=2.5.1=cpu_generic_hb0d28ef_15
  - libusb=1.0.29=hbc156a2_0
  - libutf8proc=2.10.0=h74a6958_0
  - libuv=1.51.0=h6caf38d_1
  - libvorbis=1.3.7=h81086ad_2
  - libvpx=1.14.1=h7bae524_0
  - libvulkan-loader=1.4.328.1=h49c215f_0
  - libwebp=1.6.0=hc0253d1_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.9=h4a9ca0c_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.5=h4a912ad_0
  - llvmlite=0.45.1=py310h192be34_0
  - lz4-c=1.10.0=h286801f_1
  - markdown=3.10=pyhcf101f3_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py310hf4fd40f_0
  - matplotlib-base=3.10.7=py310h0181960_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - ml_dtypes=0.4.0=py310hfd37619_2
  - moviepy=1.0.3=pyhd8ed1ab_1
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpg123=1.32.9=hf642e45_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.2=py310h0e897d2_1
  - multidict=6.6.3=py310hdf261b0_0
  - multiprocess=0.70.15=py310h2aa6e3c_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - namex=0.1.0=pyhd8ed1ab_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - nlohmann_json=3.12.0=h248ca61_1
  - nomkl=1.0=h5ca1d4c_0
  - numba=0.62.1=py310h68c42a1_0
  - numpy=2.2.6=py310h4d83441_0
  - opencv=4.11.0=headless_py310h45b86b6_2
  - openexr=3.3.2=h04410fd_0
  - openh264=2.6.0=hb5b2745_0
  - openjpeg=2.5.3=h889cd5d_1
  - openssl=3.6.0=h5503f6c_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - optree=0.17.0=py310h0e897d2_2
  - orc=2.0.3=h0ff2369_2
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h25f4b65_1
  - pango=1.56.4=h875632e_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.46=h7125dd6_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py310h5de80a5_3
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h81086ad_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - polars=1.35.1=pyh6a1acc5_0
  - polars-runtime-32=1.35.1=py310h34bb384_0
  - pooch=1.8.2=pyhd8ed1ab_3
  - proglog=0.1.10=pyhaa61c55_0
  - prometheus-cpp=1.3.0=h0967b3e_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py310hc74094e_0
  - protobuf=5.28.3=py310h853098b_0
  - psutil=7.1.3=py310hf151d32_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.15=hd3d436d_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - py-opencv=4.11.0=headless_py310hbf97dbd_2
  - pyarrow=19.0.0=py310hb6292c7_0
  - pyarrow-core=19.0.0=py310hc17921c_0_cpu
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - pysoundfile=0.13.1=pyhd8ed1ab_0
  - python=3.10.15=hdce6c4c_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-flatbuffers=25.9.23=pyh1e1bc0e_0
  - python-gil=3.10.19=hd8ed1ab_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py310h36bdd5b_1
  - python_abi=3.10=8_cp310
  - pytorch=2.5.1=cpu_generic_py310_hf92e7a3_15
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310hf4fd40f_0
  - pyzmq=27.1.0=py310hc4a7dca_0
  - qhull=2020.2=h420ef59_5
  - rav1e=0.7.1=h0716509_3
  - re2=2024.07.02=h6589ca4_2
  - readline=8.3=h0b18652_0
  - regex=2025.11.3=py310hfe3a0ae_1
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=14.2.0=pyhcf101f3_0
  - safetensors=0.6.2=py310h53169e7_2
  - scikit-learn=1.7.2=py310h660f142_0
  - scipy=1.15.2=py310h32ab4ed_0
  - sdl2=2.32.56=h248ca61_0
  - sdl3=3.2.26=h919df07_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=py310hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=hb028509_0
  - snappy=1.2.2=hada39a4_1
  - soxr=0.1.3=h5008568_3
  - soxr-python=1.0.0=py310hc7786af_1
  - sqlite=3.51.0=hab6afd1_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - standard-aifc=3.13.0=py310hbe9552e_3
  - standard-sunau=3.13.0=py310hbe9552e_3
  - statsmodels=0.14.5=py310hfdc7867_1
  - svt-av1=3.0.2=h8ab69cd_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2022.3.0=h66ce52b_1
  - tensorboard=2.18.0=pyhd8ed1ab_1
  - tensorboard-data-server=0.7.0=py310h0305fc1_3
  - tensorflow=2.18.0=cpu_py310hd689282_1
  - tensorflow-base=2.18.0=cpu_py310ha6cf98d_1
  - tensorflow-estimator=2.18.0=cpu_py310h0e61965_1
  - termcolor=3.2.0=pyhd8ed1ab_0
  - tf-keras=2.18.0=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hcd8a7d5_0
  - tokenizers=0.21.4=py310h7fe82dc_0
  - torchvision=0.20.1=py310_cpu
  - tornado=6.5.2=py310hfe3a0ae_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - transformers=4.52.4=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - ultralytics=8.3.228=pyh865f8e1_0
  - unicodedata2=17.0.0=py310hfe3a0ae_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py310hca03da5_0
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - wrapt=2.0.1=py310hfe3a0ae_1
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xxhash=0.8.3=haa4e116_0
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - yaml=0.2.5=h925e9cb_3
  - yarl=1.22.0=py310hf4fd40f_0
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h5f15de7_0
  - zstandard=0.25.0=py310hf151d32_1
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - beautifulsoup4==4.14.2
      - blinker==1.9.0
      - click==8.3.0
      - deepface==0.0.95
      - fire==0.7.1
      - flask==3.1.2
      - flask-cors==6.0.1
      - gdown==5.2.0
      - gunicorn==23.0.0
      - itsdangerous==2.2.0
      - lz4==4.4.5
      - mtcnn==1.0.0
      - retina-face==0.0.17
      - soupsieve==2.8
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/seenx
